/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meili;

import com.meilisearch.sdk.Client;
import com.meilisearch.sdk.Config;
import com.meilisearch.sdk.Task;
import com.meilisearch.sdk.Index;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            JSONArray array = new JSONArray();
            ArrayList items = new ArrayList() {{
                add(new JSONObject().put("id", "1").put("title", "Carol").put("genres",new JSONArray("[\"Romance\",\"Drama\"]")));
                add(new JSONObject().put("id", "2").put("title", "Wonder Woman").put("genres",new JSONArray("[\"Action\",\"Adventure\"]")));
                add(new JSONObject().put("id", "3").put("title", "Life of Pi").put("genres",new JSONArray("[\"Adventure\",\"Drama\"]")));
                add(new JSONObject().put("id", "4").put("title", "Mad Max: Fury Road").put("genres",new JSONArray("[\"Adventure\",\"Science Fiction\"]")));
                add(new JSONObject().put("id", "5").put("title", "Moana").put("genres",new JSONArray("[\"Fantasy\",\"Action\"]")));
                add(new JSONObject().put("id", "6").put("title", "Philadelphia").put("genres",new JSONArray("[\"Drama\"]")));
            }};

            array.put(items);
            String documents = array.getJSONArray(0).toString();
            Config config = new Config("http://meilisearch:7700", "masterKey");
            Client client = new Client(config);

            // An index is where the documents are stored.
            Index index = client.index("movies");

            // If the index 'movies' does not exist, Meilisearch creates it when you first add the documents.
            Task t = index.addDocuments(documents); // => { "uid": 0 }
            client.waitForTask(t.getUid());

            System.out.println(index.search("phi"));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
