/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javapp;

import com.meilisearch.sdk.Client;
import com.meilisearch.sdk.Config;

public class App {
    public static void main(String[] args) throws Exception {
        try {
            Client client = new Client(new Config("http://meilisearch:7700", "masterKey"));

            System.out.println(client.health());
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
